################################
## Astronomer Elasticsearch Secret
#################################
{{- if (and .Values.elasticsearch.connection (not .Values.elasticsearch.secretName)) }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-elasticsearch
  labels:
    release: {{ .Release.Name }}
    workspace: {{ .Values.platform.workspace | quote }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  connection: {{ (printf "http://%s:%s@%s:%s" .Values.elasticsearch.connection.user .Values.elasticsearch.connection.pass .Values.elasticsearch.connection.host (.Values.elasticsearch.connection.port | toString)) | b64enc | quote }}
{{- end }}
