################################
## Astronomer Prisma Service
#################################
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-prisma
  labels:
    component: prisma
    tier: astronomer
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  selector:
    component: prisma
    tier: astronomer
    release: {{ .Release.Name }}
  ports:
    - name: prisma-http
      protocol: TCP
      port: {{ .Values.ports.prismaHTTP }}
      targetPort: {{ .Values.ports.prismaHTTP }}
