# Implementation was largely taken from <https://github.com/kubernetes/git-sync/blob/2b471ba2d799/docs/kubernetes.md>
# TEST FILE DELETE BEFORE MERGING
gitSyncRelay:
  enabled: True

  repo:
    url: https://github.com/astronomer/airflow-example-dags # TODO: replace this with an example git-sync dags repo
    branch: main
    depth: 1 # default to a shallow clone because it is faster, though it sacrifices git history
    wait: 60 # seconds between synchronizations with upstream git repo
    subPath: dags # if your dags dir is not the repo root, specify the path relative to the repo root
