---
apiVersion: v1
kind: Secret
metadata:
  name: git-sync-ssh-key
data:
  # key needs to be gitSshKey
  gitSshKey: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNCcTlPdUZFOS9OQXA2aGJXR01nWURpUmdQbkIzN1NUd0Z6QXdVTFpWdXNGd0FBQUpqYkZWQU4yeFZRCkRRQUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDQnE5T3VGRTkvTkFwNmhiV0dNZ1lEaVJnUG5CMzdTVHdGekF3VUxaVnVzRncKQUFBRUNJclRpOExiOGc3eS93K3pWQm9OTlFRV0RlZkVBZWthZ2hNTFlqcHVadVRXcjA2NFVUMzgwQ25xRnRZWXlCZ09KRwpBK2NIZnRKUEFYTURCUXRsVzZ3WEFBQUFFbVJoYm1sbGJHaEFaR0Z1YVdWc2FDMXRNUUVDQXc9PQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0K
