################################
## Airflow Redis NetworkPolicy
#################################
{{- if (and .Values.networkPolicies.enabled (eq .Values.executor "CeleryExecutor")) }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-redis-policy
  labels:
    tier: airflow
    component: redis-policy
    release: {{ .Release.Name }}
    workspace: {{ .Values.platform.workspace }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  podSelector:
    matchLabels:
      tier: airflow
      component: redis
      release: {{ .Release.Name }}
      workspace: {{ .Values.platform.workspace | quote }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          tier: airflow
          component: worker
          release: {{ .Release.Name }}
          workspace: {{ .Values.platform.workspace | quote }}
    - podSelector:
        matchLabels:
          tier: airflow
          component: scheduler
          release: {{ .Release.Name }}
          workspace: {{ .Values.platform.workspace | quote }}
    - podSelector:
        matchLabels:
          tier: airflow
          component: flower
          release: {{ .Release.Name }}
          workspace: {{ .Values.platform.workspace | quote }}
    ports:
    - protocol: TCP
      port: {{ .Values.ports.redisDB }}
{{- end }}
