################################
## Airflow Scheduler ServiceAccount
#################################
{{- if .Values.rbacEnabled }}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-scheduler-serviceaccount
  labels:
    tier: airflow
    release: {{ .Release.Name }}
    workspace: {{ .Values.platform.workspace | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
{{- end }}
