################################
## Airflow Scheduler NetworkPolicy
#################################
{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-scheduler-policy
  labels:
    tier: airflow
    component: airflow-scheduler-policy
    release: {{ .Release.Name }}
    workspace: {{ .Values.platform.workspace | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  podSelector:
    matchLabels:
      tier: airflow
      component: scheduler
      release: {{ .Release.Name }}
      workspace: {{ .Values.platform.workspace | quote }}
  policyTypes:
  - Ingress
{{- if (or (eq .Values.executor "LocalExecutor") (eq .Values.executor "SequentialExecutor")) }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          tier: airflow
          component: webserver
          release: {{ .Release.Name }}
          workspace: {{ .Values.platform.workspace | quote }}
    ports:
    - protocol: TCP
      port: {{ .Values.ports.workerLogs }}
{{- end }}
{{- end }}
