################################
## Airflow Webserver NetworkPolicy
#################################
{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-webserver-policy
  labels:
    tier: airflow
    component: airflow-webserver-policy
    release: {{ .Release.Name }}
    workspace: {{ .Values.platform.workspace | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  podSelector:
    matchLabels:
      tier: airflow
      component: webserver
      release: {{ .Release.Name }}
      workspace: {{ .Values.platform.workspace | quote }}
  policyTypes:
  - Ingress
{{- if .Values.platform.release }}
  ingress:
  - from:
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          tier: nginx
          component: ingress-controller
          release: {{ .Values.platform.release }}
    ports:
    - protocol: TCP
      port: {{ .Values.ports.airflowUI }}
{{- end }}
{{- end }}
