################################
## Astronomer Houston Deployment
#################################
kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: {{ .Release.Name }}-houston
  labels:
    component: houston
    tier: astronomer
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: astronomer
      component: houston
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        tier: astronomer
        component: houston
        release: {{ .Release.Name }}
      annotations:
        checksum/houston-config: {{ include (print $.Template.BasePath "/houston/houston-configmap.yaml") . | sha256sum }}
    spec:
      nodeSelector:
{{ toYaml (default .Values.global.platformNodePool.nodeSelector .Values.nodeSelector) | indent 8 }}
      affinity:
{{ toYaml (default .Values.global.platformNodePool.affinity .Values.affinity) | indent 8 }}
      tolerations:
{{ toYaml (default .Values.global.platformNodePool.tolerations .Values.tolerations) | indent 8 }}
      restartPolicy: Always
      {{- if and (not .Values.houston.airflowBackendSecretName) (not .Values.houston.airflowBackendConnection) }}
      serviceAccountName: {{ template "houston.bootstrapperServiceAccount" . }}
      initContainers:
        - name: houston-bootstrapper
          image: {{ template "dbBootstrapper.image" . }}
          imagePullPolicy: {{ .Values.images.dbBootstrapper.pullPolicy }}
          env:
            - name: BOOTSTRAP_DB
              valueFrom:
                secretKeyRef:
                  name: astronomer-bootstrap
                  key: connection
            - name: DB_NAME
              value: {{ .Release.Name }}-houston
            - name: SECRET_NAME
              value: {{ template "houston.airflowBackendSecret" . }}
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: IN_CLUSTER
              value: "true"
      {{- end }}
      containers:
        - name: houston
          image: {{ template "houston.image" . }}
          imagePullPolicy: {{ .Values.images.houston.pullPolicy }}
          resources:
{{ toYaml .Values.houston.resources | indent 12 }}
          {{- if .Values.global.tlsSecret }}
          volumeMounts:
            {{- include "houston_volume_mounts" . | indent 12 }}
          {{- end }}
          ports:
            - name: houston-http
              containerPort: {{ .Values.ports.houstonHTTP }}
          livenessProbe:
            httpGet:
              path: /v1/healthz
              port: {{ .Values.ports.houstonHTTP }}
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /v1/healthz
              port: {{ .Values.ports.houstonHTTP }}
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 10
          env:
            {{- include "houston_environment" . | indent 12 }}
      volumes:
        - name: houston-config-volume
          configMap:
            name: {{ .Release.Name }}-houston-config
            items:
              - key: production.yaml
                path: production.yaml
              - key: local-production.yaml
                path: local-production.yaml
        - name: houston-jwt-key-volume
          secret:
            secretName: {{ template "houston.jwtKeySecret" . }}
        - name: houston-jwt-certificate-volume
          secret:
            secretName: {{ template "houston.jwtCertificateSecret" . }}
    {{ if .Values.global.tlsSecret }}
        - name: registry-tls-volume
          secret:
            secretName: {{ .Values.global.tlsSecret }}
    {{- end }}
