################################
## Astronomer Houston Deployment
#################################
kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: {{ .Release.Name }}-houston
  labels:
    component: houston
    tier: astronomer
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: astronomer
      component: houston
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        tier: astronomer
        component: houston
        release: {{ .Release.Name }}
      annotations:
        checksum/houston-config: {{ include (print $.Template.BasePath "/houston/houston-configmap.yaml") . | sha256sum }}
    spec:
      restartPolicy: Always
      containers:
        - name: {{ .Release.Name }}-houston
          image: {{ template "houston.image" . }}
          imagePullPolicy: {{ .Values.images.houston.pullPolicy }}
          resources:
{{ toYaml .Values.houston.resources | indent 12 }}
          {{- if .Values.global.tlsSecret }}
          volumeMounts:
            - name: houston-config-volume
              mountPath: /houston/config/production.yaml
              subPath: production.yaml
            - name: houston-config-volume
              mountPath: /houston/config/local-production.yaml
              subPath: local-production.yaml
            - name: registry-tls-volume
              mountPath: /etc/houston/tls
          {{- end }}
          ports:
            - name: houston-http
              containerPort: {{ .Values.ports.houstonHTTP }}
          livenessProbe:
            httpGet:
              path: /v1/healthz
              port: {{ .Values.ports.houstonHTTP }}
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /v1/healthz
              port: {{ .Values.ports.houstonHTTP }}
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 10
          env:
            {{- range $i, $config := .Values.houston.env }}
            - name: {{ $config.name }}
              value: {{ $config.value | quote }}
              {{- end }}
            - name: NODE_ENV
              value: "production"
            - name: REGISTRY_CERT_PATH
              value: /etc/houston/tls/
            - name: REGISTRY_ISSUER
              value: {{ .Values.registry.auth.issuer }}
            - name: REGISTRY_SERVICE
              value: {{ .Values.registry.auth.service }}
            {{- if .Values.global.baseDomain }}
            - name: REGISTRY_AUTH
              valueFrom:
                secretKeyRef:
                  name: {{ template "registry.authSecret" . }}
                  key: .dockerconfigjson
            {{- end }}
            - name: JWT_PASSPHRASE
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-houston-jwt-passphrase
                  key: passphrase
            - name: PRISMA_MANAGEMENT_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-prisma-secret
                  key: api-secret
            - name: PRISMA_ENDPOINT
              value: {{ template "prisma.endpoint" . }}
            - name: PRISMA_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-prisma-secret
                  key: service-secret
            - name: DEPLOYMENTS_DATABASE_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: {{ template "houston.airflowBackendSecret" . }}
                  key: connection
      volumes:
        - name: houston-config-volume
          configMap:
            name: {{ .Release.Name }}-houston-config
            items:
              - key: production.yaml
                path: production.yaml
              - key: local-production.yaml
                path: local-production.yaml
    {{ if .Values.global.tlsSecret }}
        - name: registry-tls-volume
          secret:
            secretName: {{ .Values.global.tlsSecret }}
    {{- end }}
