############################
## git-sync NetworkPolicy ##
############################
# https://kubernetes.io/docs/concepts/services-networking/network-policies/

{{- if .Values.airflow.dags.gitSync.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-git-sync
  labels:
    component: git-sync
    tier: airflow
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  podSelector:
    matchLabels:
      tier: astronomer
      component: git-sync
      release: {{ .Release.Name }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          release: {{ .Release.Name }}
          tier: airflow
    ports:
    - protocol: TCP
      port: {{ .Values.airflow.dags.gitSync.port }}
{{- end -}}
