#########################
## git-sync Deployment ##
#########################
{{- if .Values.airflow.dags.gitSync.enabled }}
# Largely taken from <https://github.com/kubernetes/git-sync/blob/2b471ba2d799/docs/kubernetes.md>

apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-sync-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: git-sync-example
  template:
    metadata:
      labels:
        app: git-sync-example
    spec:
      securityContext:
        fsGroup: {{ .Values.airflow.dags.gitSync.uid }}
      volumes:
        - name: git-repo-contents
          emptyDir: {}
        - name: git-secret
          secret:
            secretName: git-creds
            defaultMode: 0400
      containers:
        - name: "{{ .Values.airflow.dags.gitSync.repo }}"
          # This container pulls git data and publishes it into volume
          # "git-repo-contents".  In that volume you will find a symlink
          # "current" (see -dest below) which points to a checked-out copy of
          # the master branch (see -branch) of the repo (see -repo).
          # NOTE: git-sync already runs as non-root.
          image: k8s.gcr.io/git-sync:v4.0.0
          args:
            - "--repo={{ .Values.airflow.dags.gitSync.repo }}"
            - "--branch={{ .Values.airflow.dags.gitSync.branch }}"
            - "--depth={{ .Values.airflow.dags.gitSync.depth }}"
            - "--period={{ .Values.airflow.dags.gitSync.wait }}"
            - "--link=current"
            - "--root={{ .Values.airflow.dags.gitSync.root }}"
          volumeMounts:
            - name: git-secret
              mountPath: /etc/git-secret
              readOnly: true
            - name: git-repo-contents
              mountPath: /git
        - name: server
          # This container serves the data pulled from git, via the volume
          # "git-repo-contents".
          # NOTE: apache runs as root to expose port 80, and there's not a
          # trivial flag to change that.  Real servers should not run as root
          # when possible.
          image: httpd:alpine
          volumeMounts:
            - name: git-repo-contents
              mountPath: /usr/local/apache2/htdocs/
              readOnly: true # no need to ever write to the volume
{{- end -}}
