################################
## Prometheus Service
#################################
kind: Service
apiVersion: v1
metadata:
  name: {{ template "prometheus.fullname" . }}
  labels:
    tier: monitoring
    component: {{ template "prometheus.name" . }}
    chart: {{ template "prometheus.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  selector:
    tier: monitoring
    component: {{ template "prometheus.name" . }}
    release: {{ .Release.Name }}
  ports:
    - name: prometheus-data
      protocol: TCP
      port: {{ .Values.ports.http }}
      targetPort: {{ .Values.ports.http }}
