################################
## Orbit NetworkPolicy
#################################
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-orbit-policy
  labels:
    tier: astronomer
    component: orbit-policy
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  podSelector:
    matchLabels:
      tier: astronomer
      component: orbit
      release: {{ .Release.Name }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          tier: nginx
          component: ingress-controller
    ports:
    - protocol: TCP
      port: {{ .Values.ports.orbitHTTP }}
