################################
## OAuth2 Proxy Secret
#################################
{{ $random_cookie_secret := randAlphaNum 32 | b64enc }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    tier: airflow
    component: webserver
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
{{- with .Values.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
  name: {{ printf "%s-oauth2-proxy" .Release.Name }}
type: Opaque
data:
  cookie-secret: {{ default $random_cookie_secret .Values.oauth2.cookieSecret | b64enc | quote }}
  client-secret: {{ .Values.oauth2.clientSecret | b64enc | quote }}
  client-id: {{ .Values.oauth2.clientID | b64enc | quote }}
