################################
## Airflow Webserver Service
#################################
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-webserver
  labels:
    tier: airflow
    component: webserver
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
{{- with .Values.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.webserver.service.type | default "ClusterIP" }}
  {{- if .Values.webserver.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.webserver.service.loadBalancerIP }}
  {{- end }}
  selector:
    tier: airflow
    component: webserver
    release: {{ .Release.Name }}
  ports:
    # - name: airflow-ui
    #   protocol: TCP
    #   port: {{ .Values.ports.airflowUI }}
    #   targetPort: {{ .Values.ports.airflowUI }}
    - name: oathkeeper
      protocol: TCP
      port: 8080
      targetPort: 4455
    - name: oathkeeper-api
      protocol: TCP
      port: 8081
      targetPort: 4456
