################################
## Airflow Metadata Secret
#################################
{{- if (and .Values.data.metadataConnection (not .Values.data.metadataSecretName)) }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-airflow-metadata
  labels:
    release: {{ .Release.Name }}
    workspace: {{ .Values.platform.workspace | quote }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  connection: {{ (printf "postgresql://%s:%s@%s:%s/%s" .Values.data.metadataConnection.user .Values.data.metadataConnection.pass (ternary (printf "%s-%s" .Release.Name "pgbouncer") .Values.data.metadataConnection.host .Values.pgbouncer.enabled) ((ternary .Values.ports.pgbouncer .Values.data.metadataConnection.port .Values.pgbouncer.enabled) | toString) (ternary (printf "%s-%s" .Release.Name "metadata") .Values.data.metadataConnection.db .Values.pgbouncer.enabled)) | b64enc | quote }}
{{- end }}
