################################
## Pgbouncer Stats Secret
#################################
{{- if .Values.pgbouncer.enabled }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ template "pgbouncer_stats_secret" . }}
  labels:
    release: {{ .Release.Name }}
    workspace: {{ .Values.platform.workspace | quote }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  connection: {{ (printf "postgresql://%s:%s@127.0.0.1:%s/pgbouncer?sslmode=disable" .Values.data.metadataConnection.user .Values.data.metadataConnection.pass (.Values.ports.pgbouncer | toString)) | b64enc | quote }}
{{- end }}
