###############################
## git-sync-relay Deployment ##
###############################
{{- if .Values.gitSyncRelay.enabled }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-git-sync-relay
  labels:
    component: git-sync-relay
    tier: airflow
    release: {{ .Release.Name }}
    chart: "{{ .Release.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: git-sync-relay
      tier: airflow
  template:
    metadata:
      labels:
        component: git-sync-relay
        tier: airflow
        release: {{ .Release.Name }}
        chart: "{{ .Release.Name }}-{{ .Chart.Version }}"
        heritage: {{ .Release.Service }}
    spec:
      securityContext:
        fsGroup: {{ .Values.gitSyncRelay.uid }}
      volumes:
        - name: git-repo-contents
          emptyDir: {}
        - name: git-secret
          secret:
            secretName: {{ .Release.Name }}-upstream-git-credentials
            defaultMode: 0400
      containers:
        - name: "git-sync"
          image: "{{ .Values.gitSyncRelay.images.gitSync.repository }}:{{ .Values.gitSyncRelay.images.gitSync.tag }}"
          args:
            # https://github.com/kubernetes/git-sync#parameters
            - "--repo={{ .Values.gitSyncRelay.repo.url }}"
            - "--branch={{ .Values.gitSyncRelay.repo.branch }}"
            - "--depth={{ .Values.gitSyncRelay.repo.depth }}"
            - "--wait={{ .Values.gitSyncRelay.repo.wait }}"
            - "--root=/git"
          volumeMounts:
            - name: git-secret
              mountPath: /etc/git-secret
              readOnly: true
            - name: git-repo-contents
              mountPath: /git
        - name: git-daemon
          image: "{{ .Values.gitSyncRelay.images.gitDaemon.repository }}:{{ .Values.gitSyncRelay.images.gitDaemon.tag }}"
          volumeMounts:
            - name: git-repo-contents
              mountPath: /git
              readOnly: False
          env:
            - name: GIT_ROOT
              value: "/git"
        - name: "debug"
          image: quay.io/danielhoherd/uw:latest
          command:
            - /bin/sleep
            - infinity
          volumeMounts:
            - name: git-repo-contents
              mountPath: /git
              readOnly: False
{{- end -}}
