############################
## git-sync-relay Service ##
############################
{{- if .Values.airflow.dags.gitSync.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-git-sync-relay
  labels:
    component: git-sync-relay
    tier: airflow
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
{{- end -}}
