##################################
## git-sync-relay NetworkPolicy ##
##################################
# https://kubernetes.io/docs/concepts/services-networking/network-policies/

{{- if .Values.gitSyncRelay.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-git-sync-relay
  labels:
    component: git-sync-relay
    tier: airflow
    release: {{ .Release.Name }}
    chart: "{{ .Release.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  podSelector:
    matchLabels:
      tier: astronomer
      component: git-sync-relay
      release: {{ .Release.Name }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          release: {{ .Release.Name }}
          tier: airflow
    ports:
    - protocol: TCP
      # port: {{ .Values.airflow.dags.gitSync.port }}
      port: 80
{{- end -}}
