################################
## Airflow Worker Service
#################################
{{- if eq .Values.executor "CeleryExecutor" }}
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-worker
  labels:
    tier: airflow
    component: worker
    release: {{ .Release.Name }}
    workspace: {{ .Values.platform.workspace | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  clusterIP: None
  selector:
    tier: airflow
    component: worker
    release: {{ .Release.Name }}
    workspace: {{ .Values.platform.workspace | quote }}
  ports:
    - name: worker-logs
      protocol: TCP
      port: {{ .Values.ports.workerLogs }}
      targetPort: {{ .Values.ports.workerLogs }}
{{- end }}
