################################
## Airflow Worker NetworkPolicy
#################################
{{- if (and .Values.networkPolicies.enabled (eq .Values.executor "CeleryExecutor")) }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-worker-policy
  labels:
    tier: airflow
    component: airflow-worker-policy
    release: {{ .Release.Name }}
    workspace: {{ .Values.platform.workspace | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  podSelector:
    matchLabels:
      tier: airflow
      component: worker
      release: {{ .Release.Name }}
      workspace: {{ .Values.platform.workspace | quote }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          tier: airflow
          release: {{ .Release.Name }}
          component: webserver
          workspace: {{ .Values.platform.workspace | quote }}
    ports:
    - protocol: TCP
      port: {{ .Values.ports.workerLogs }}
{{- end }}
