#### borrowed astronomer default deny network policy ####
#### TODO: delete this before merge
{{- if .Values.defaultDenyNetworkPolicy }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-default-deny-ingress
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
{{- end -}}
