################################
## Airflow Namespace ResourceQuota
#################################
{{- if .Values.quotas }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Release.Name }}-resource-quota
  labels:
    tier: resources
    component: resourcequota
    release: {{ .Release.Name }}
    workspace: {{ .Values.platform.workspace | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  hard:
{{ toYaml .Values.quotas | indent 4 }}
{{- end }}
