################################
## Kubed NetworkPolicy
#################################
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "kubed.fullname" . }}-policy
  labels:
    tier: {{ template "kubed.name" . }}
    component: {{ template "kubed.name" . }}
    chart: {{ template "kubed.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  podSelector:
    matchLabels:
      tier: {{ template "kubed.name" . }}
      component: {{ template "kubed.name" . }}
      release: {{ .Release.Name }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          tier: monitoring
          component: prometheus
          release: {{ .Release.Name }}
    ports:
    - protocol: TCP
      port: {{ .Values.service.targetPort }}
