################################
## KubeD Service
#################################
apiVersion: v1
kind: Service
metadata:
  name: {{ template "kubed.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    tier: {{ template "kubed.name" . }}
    component: {{ template "kubed.name" . }}
    chart: {{ template "kubed.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.service.port | quote }}
spec:
  type: ClusterIP
  ports:
  # Port used to expose admission webhook apiserver
  - name: kubed-api
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
    tier: {{ template "kubed.name" . }}
    component: {{ template "kubed.name" . }}
    release: {{ .Release.Name }}
